### ISSUE TITLE
Schematics should have a white background

### ISSUE THREAD

**Issue by seveibar** [tscircuit/circuit-to-svg#13]

**Comment by imrishabh18** [comment]
Are you seeing the background color as white, cause even with the system preference as dark and light. The background color always stays white for me

<img width="1754" alt="Screenshot 2024-08-22 at 7 22 38 PM" src="https://github.com/user-attachments/assets/5645d724-7fee-4c5e-ae3c-d903a9cff6a9">

**Comment by seveibar** [comment]
i wonder if we can just add a style to the svg, for me it's only white in the storybook but takes the background color on e.g. vs code
