### ISSUE TITLE
Rename `pcbSoupToSvg` to `convertCircuitJsonToPcbSvg`, rename `soupToSvg` to `convertCircuitJsonToSchematicSvg`

### ISSUE THREAD

**Issue by seveibar** [tscircuit/circuit-to-svg#33]

**Comment by imrishabh18** [comment]
@seveibar This issue was already resolved sometime back, 
https://github.com/tscircuit/circuit-to-svg/blob/fdf9bde2ef0bfd612bb157759c4aff847245d376/src/lib/pcb-soup-to-svg.ts#L13

https://github.com/tscircuit/circuit-to-svg/blob/fdf9bde2ef0bfd612bb157759c4aff847245d376/src/lib/soup-to-svg.ts#L5

**Comment by seveibar** [comment]
Ah i must have an old dependency or something

**Comment by seveibar** [comment]
Fwiw the filenames are still the old version, maybe i made the issue after a quick look at the files

**Comment by imrishabh18** [comment]
Renamed it!
