### ISSUE TITLE
Fix: Layout of smtpad

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/circuit-to-svg#40]
pcb-viewer

<img width="837" alt="Screenshot 2024-09-02 at 1 16 03 AM" src="https://github.com/user-attachments/assets/4f0509ab-950d-40a8-b63b-002bbc530b02">

https://debug.tscircuit.com/soup_group/core_example1#%7B%22selected_engine%22%3A%22pcb%22%2C%22selected_layout_index%22%3A0%7D

Circuit-to-svg

<img width="1099" alt="Screenshot 2024-09-02 at 1 17 09 AM" src="https://github.com/user-attachments/assets/7ea85122-6bcf-42d0-ae51-79045646d582">

**Comment by seveibar** [comment]
@imrishabh18, i think this was actually fixed by core, core/builder will automatically compute the final positions and shapes of smtpads because circuit json is supposed to be "fully computed", so the renderer doesn't need to perform the rotation!
