### ISSUE TITLE
Create this scene in circuit-to-svg

### ISSUE THREAD

**Issue by seveibar** [tscircuit/circuit-to-svg#79]
- ignore grid

![image](https://github.com/user-attachments/assets/132f83a5-bb44-4e95-9ac1-707222dd8f47)

**Comment by imrishabh18** [comment]
@seveibar How's this? 
<img width="1431" alt="Screenshot 2024-10-01 at 6 36 04 PM" src="https://github.com/user-attachments/assets/3f77040b-9a36-4fa0-b557-fe83fb96896f">

Question: The schematic symbols have text {REF} and {VAL} but currently we are not taking a props as an input for that in the svg generation

**Comment by seveibar** [comment]
![image](https://github.com/user-attachments/assets/2cf5b2aa-53dd-47ec-8df2-7aea4a1ef45e)

**Comment by seveibar** [comment]
`getSvg` could take optional parameters for `{ displayName, displayValue }`
